name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: kelvynpaiva
        password: ${{secrets.PASSWORD_DOCKER_HUB}}

    - name: Construir e enviar imagens Docker
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kelvynpaiva/curso_ci-cd_alura:${{github.ref_name}}