name: Entrega contínua no ECS

on:
  workflow_call: 

jobs:
    ECS:
        runs-on: ubuntu-latest
        steps:

          - name: Configurando credenciais da AWS
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO_AWS }}
              aws-secret-access-key: ${{ secrets.CHAVE_SECRETA_AWS }}
              aws-region: us-east-2 #(Ohaio)

          - name: Obtendo arquivo da tarefa
            run: aws ecs describe-task-definition --task-definition tarefa_de_cluster_ci-cd_alura --query taskDefinition > task-definition.json

          - name: Cópia do task-definition
            run: cp task-definition.json task-definition.json.old

          - name: Preencha o novo ID da imagem na definição de tarefa do Amazon ECS
            id: task-def
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
                task-definition: task-definition.json
                container-name: Go
                image: kelvynpaiva/curso_ci-cd_alura:${{github.run_number}}
                environment-variables: |
                  HOST=${{ secrets.DBHOST }}
                  USER=${{ secrets.DBUSER }}
                  PASSWORD=${{ secrets.DBPASSWORD }}
                  DBNAME=${{ secrets.DBNAME }}
                  DBPORT=${{ secrets.DBPORT }}
                  PORT=8000

          - name: Deploy de tarefa do Amazon ECS
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: servico_curso_ci-cd_alura
                cluster: cluster-curso-ci-cd-alura
                wait-for-service-stability: true